version: "3.9"
services:
  mongo_db:
    image: mongo:latest
    container_name: orders_mongo_db
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-idosell}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-root}
    restart: always
  api:
    build:
      context: .
      dockerfile: app/api/dockerfile
    image: api:latest
    ports:
      - "${API_PORT}:3000"
    environment:
      - NODE_ENV=production
  worker:
    build:
      context: .
      dockerfile: app/worker/dockerfile
    image: worker:latest
