FROM node:23-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY app/api ./app/api
COPY tsconfig.json ./
COPY app/api/tsconfig.json ./app/api/
COPY app/share/mongo-lib ./app/share/mongo-lib
RUN npm run build:api

EXPOSE 3000

CMD ["npm", "start:api"]