services:
  mongo_db:
    image: mongo:latest
    container_name: db_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-idosell}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-root}
    healthcheck:
      test:
        [
          "CMD",
          "mongosh",
          "--quiet",
          "127.0.0.1:27017/admin",
          "-u",
          "${DB_USER:-root}",
          "-p",
          "${DB_PASSWORD:-root}",
          "--eval",
          "db.adminCommand('ping')",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: always

  api:
    build:
      context: .
      dockerfile: packages/api/dockerfile
    image: api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      mongo_db:
        condition: service_healthy
    restart: always
  worker:
    build:
      context: .
      dockerfile: packages/worker/dockerfile
    image: worker:latest
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      mongo_db:
        condition: service_healthy
    restart: always
