services:
  mongo_db:
    image: mongo:latest
    container_name: db_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME:-idosell}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD:-root}
    restart: always

  api:
    build:
      context: .
      dockerfile: packages/api/dockerfile
    image: api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongo_db
    restart: always
  worker:
    build:
      context: .
      dockerfile: packages/worker/dockerfile
    image: worker:latest
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - mongo_db
    restart: always
